accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'
urlpatterns = [
    path('login/',login_view,name='login'),
    path('register/',register_view,name='register'),
    path('logout/',logout_view,name='logout'),
]

app/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import homeview,katil_post
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import login_view
from accounts.views import register_view
from accounts.forms import LoginForm
from home.views import login_redirect
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',homeview,name='home'),
    path('home/',include('home.urls')),
    path('', login_redirect, name='login_redirect'),
    path('accounts/',include('accounts.urls')),
    path('post/',include('post.urls')),
    
 
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name='home'
urlpatterns = [
    path('connect/<operation>/<int:pk>/', change_friends, name='change_friends'),
    path('katil/<int:id>/',katil_post,name='katil_post'),

]

home/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from post.models import post

# Create your models here.
class HomePost(models.Model):
     title=models.CharField(max_length=120)
     user = models.ForeignKey(User,
            on_delete=models.CASCADE)
     katilimci=models.ManyToManyField(User, related_name='katilimci', blank=True)
     content=models.TextField()
     publishing_date=models.DateTimeField(auto_now_add=True)
     image=models.FileField(null=True,blank=True)

     def __str__(self):
         return self.title
     def get_absolute_url1(self):
         return reverse('home:katil',kwargs={'id':self.id})


     class Meta:
         ordering=['-publishing_date']
class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True,on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

home/forms.py
from django import forms
from .models import HomePost


class HomeForm(forms.ModelForm):

	class Meta:
		model=HomePost
		fields=[
			'title',
            'user',
			'content',
            'image',
			]

home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from .models import HomePost,Friend
from .forms import HomeForm
from post.forms import *
from post.urls import *
from django.urls import reverse

# Create your views here.


def login_redirect(request):
    return redirect('/accounts/login/')

def homeview(request):

    context={
            'isim':'Misafir',
            }
    form = HomeForm()
    posts = post.objects.all()
    kisi_post=post.objects.filter(user=request.user)
    
    try:
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    except Friend.DoesNotExist:
        friends = None
    users = User.objects.exclude(id=request.user.id)
    args = {
            'form': form, 'posts': posts, 'users': users, 'friends':friends,'kisi_post':kisi_post}
        
   
    return render(request,'home.html',args)
def katil_post(request,id):
    post1=post.objects.get(id=id)
    post1.katilimci.add(request.user)
    return redirect('home')

def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('home')

templates/home.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<style>
    button {
        background-color: #4CAF50;
        color: white;
        padding: 100px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }
    </style>
<body>
   
    <div class="w3-top">
        <div class="w3-bar w3-theme-d2 w3-left-align w3-large">

            <img src="C:\Users\hp_\Downloads\Sosyal_Platform_Projesi\Sosyal_Platform_Projesi\logo.png" width="40" height="40">
            <a class="active" href=><i class="fa fa-fw fa-home"></i> Home</a>
            <a class="active" href="C:\Users\Berkin\Desktop\Sosyal_Platform_Projesi\Message.html"><i class="fa fa-fw fa-envelope"></i> Message</a>
            <a class="active" href="C:\Users\Berkin\Desktop\Sosyal_Platform_Projesi\Users.html"><i class="fa fa-fw fa-user"></i> Profile</a>
            <a class="active" href="#"><i class="fa fa-fw fa-search"></i> Search</a>
            <a href="{% url 'accounts:logout'  %}"
                 style="float:right;" class="active" ><i class="fa fa-fw fa-sign-out"></i> Exit</></a>
                <a style="float:right;" class="active" href="#"><i class="fa fa-fw fa-question-circle"></i>Question</a>


            </a>
        </div>
    </div>
        <a href="http://127.0.0.1:8000/post/create/">
            <button type="button" class="btn btn-success">POST OLUŞTUR</button>
    </a>

    <div class="w3-col m3">
        <div class="w3-card w3-round">
            <div class="w3-white">
                <button onclick="myFunction('Demo1')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-circle-o-notch fa-fw w3-margin-right"></i> My Groups</button>
                <div id="Demo1" class="w3-hide w3-container">
                   
                </div>

                <button onclick="myFunction('Demo2')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-calendar-check-o fa-fw w3-margin-right"></i> My Friends</button>
                <div id="Demo2" class="w3-hide w3-container">
                    {% if friends %}
                    {% for friend in friends %}
                    <h3>{{ friend.username }}</h3>
                    <a href="{% url 'home:change_friends' operation='remove'  pk=friend.pk %}">
                        <button class="w3-button w3-block w3-red w3-section" title="Decline"><i class="fa fa-remove"></i></button>
                    </a>

                    {% endfor %}
                    {% endif %}
                </div>

                <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-calendar-check-o fa-fw w3-margin-right"></i> My Events</button>
                <div id="Demo3" class="w3-hide w3-container">
                    {% if kisi_post %}
                    {% for kisi_posta in kisi_post %}
                    <h3>
                        <a href="{{kisi_posta.get_absolute_url}}">{{kisi_posta.title}}</a><h3>
    <br />
    

            {% endfor %}
            {% endif %}
</div>


                <button onclick="myFunction('Demo4')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-users fa-fw w3-margin-right"></i> My Photos</button>
                <div id="Demo4" class="w3-hide w3-container">
                    <div class="w3-row-padding">
                        <br>
                        <div class="w3-half">
                            <img src="/w3images/lights.jpg" style="width:100%" class="w3-margin-bottom">
                        </div>
                        <div class="w3-half">
                            <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
                        </div>
                        <div class="w3-half">
                            <img src="/w3images/mountains.jpg" style="width:100%" class="w3-margin-bottom">
                        </div>
                        <div class="w3-half">
                            <img src="/w3images/forest.jpg" style="width:100%" class="w3-margin-bottom">
                        </div>

                    </div>
                </div>
            </div>
        </div>
        </div>
        <br>


        <div class="w3-col m7">
            <div class="w3-container w3-card w3-white w3-round w3-margin">
                
                {%for post in posts%}
                <div class="w3-container w3-card w3-white w3-round w3-margin">
                    <br>

                    <h1 style="color:forestgreen;">{{post.title}}</h1><br />
                    <p1 style="color:red">{{post.user}}</p1><br>
                    {{post.publishing_date}}<br />

                    <span class="w3-right w3-opacity">32 min</span>

                    {%if post.image %}
                    <img src="{{post.image.url}}" style="width:100%" class="w3-margin-bottom">
                    {%endif%}
                    <p>{{post.content}}</p>
                    <a href="{% url 'home:katil_post' id=post.id %}">
                        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>KATIL</button>
                    </a>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>


    <div class="w3-col m2">
        <div class="w3-card w3-round w3-white w3-center">
            <div class="w3-container">
                {% for user in users %}
                {% if not user in friends %}
                <h3>{{ user.username }}</h3>
                <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">

                    <button class="w3-button w3-block w3-green w3-section" title="Accept"><i class="fa fa-check"></i></button>

                </a>
                {% endif %}
                {% endfor %}
                



            </div>
        </div>
        <br>





</body>
</html>








<title>ActDo</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    html, body, h1, h2, h3, h4, h5 {
        font-family: "Open Sans", sans-serif
    }
</style>


    <!-- Footer -->
    <!-- <footer class="w3-container w3-theme-d3 w3-padding-16">
      <h5>Footer</h5>
    </footer>-->


    <script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else {
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className =
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
    </script>

</body>
</html>