app/urls.py
from django.contrib import admin
from django.urls import path,include
from home.views import homeview,katil_post
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import login_view
from accounts.views import register_view
from accounts.forms import LoginForm
from home.views import login_redirect
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',homeview,name='home'),
    path('home/',include('home.urls')),
    path('', login_redirect, name='login_redirect'),
    path('accounts/',include('accounts.urls')),
    path('post/',include('post.urls')),
    
 
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *
from django.conf.urls import url
app_name='post'
urlpatterns = [
    path('<int:id>/', post_detail, name='detail'),
    path('<int:id>/', post_detay, name='detay'),
    path('index/',post_index),
    path('create/',post_create),
    path('<int:id>/delete',post_delete,name='delete'),
    path('<int:id>/update/',post_update,name='update'),
    path('katilim/',post_katilim,name='katilimci'),

   
]

post/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
# Create your models here.
class post(models.Model):
     title=models.CharField(max_length=120)
     user = models.ForeignKey(User,
            on_delete=models.CASCADE)
     katilimci=models.ManyToManyField(User, related_name='katilimcii', blank=True)
     content=models.TextField()
     publishing_date=models.DateTimeField(auto_now_add=True)
     image=models.FileField(null=True,blank=True)

     def __str__(self):
         return self.title
     def get_absolute_url(self):
         return reverse('post:detail',kwargs={'id':self.id})
     def get_absoluto(self):
         return reverse('post:detay',kwargs={'id':self.id})
     class Meta:
         ordering=['-publishing_date']
     
    
class Katilim(models.Model):
    posta=models.ForeignKey(post,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

     
            

post/forms.py
from django import forms
from .models import post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

	class Meta:
		model=post
		fields=[
			'title',
			'content',
            'image',
			]

post/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,redirect
from .models import post,Katilim
from django.http import HttpResponseRedirect
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.models import User
from django import forms

def post_katilim(request):
    katilimcilar=Katilim.objects.filter(post=post).order_by('-id')
    args={
        'katilimcilar':katilimcilar,
        }
    return render(request,'post/katilim.html',args)
def post_detay(request,id):
    posta=post.objects.get(id=id)
    katilimcilar=posta.katilimci.all()
    users = User.objects.exclude(id=request.user.id)
    return render(request,'post/detay.html',{'posta':posta,'users':users,'katilimcilar':katilimcilar})
def post_detail(request,id):
    
     
    posta=post.objects.get(id=id)
    katilimcilar=posta.katilimci.all()
    users = User.objects.exclude(id=request.user.id)
    return render(request,'post/detail.html',{'posta':posta,'users':users,'katilimcilar':katilimcilar})
def post_index(request):
     users = User.objects.exclude(id=request.user.id)
     posts=post.objects.all()
     args = {
             'posts': posts, 'users': users, 
        }
   
     return render(request,'post/index.html',args)
def post_create(request):

    form=PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('home')
   
    context={
        'form':form,
        }
    return render(request,'post/form.html',context)

    
def post_delete(request,id):
    posta=post.objects.get(id=id)
    posta.delete()
    return redirect('home')

def post_update(request,id):
    posta=post.objects.get(id=id)
    form=PostForm(request.POST or None,request.FILES or None,instance=posta)
    if form.is_valid():
        posta = form.save(commit=False)
        posta.user = request.user
        posta.save()
        return redirect('home')
   
    context={
        'form':form,
        }
    return render(request,'post/form.html',context)
    return()
    

templates/post/detail.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    {{posta.id}}<br />
    {{posta.title}}<br />
    {{posta.content}}<br />
    {{posta.user}}<br />
    {{posta.publishing_date}}<br />
    
    {%if posta.image %}
    <img src="{{posta.image.url}}" class=" img-responsive"<br />
    {%endif%}<br />

    {%if posta.katilimci %}
    {%for i in katilimcilar%}
    {{i}}
    {%endfor%}
    {%endif%}<br />
    <a href="{% url 'post:delete' id=posta.id %}">
        <button type="button" class="btn btn-success">sil</button>
    </a>
    <a href="{% url 'post:update' id=posta.id %}">
        <button type="button" class="btn btn-success">Güncelle</button>
    </a>

</body>
</html>

templates/post/detay.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<style>
    button {
        background-color: #4CAF50;
        color: white;
        padding: 24px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }
</style>
<body>




    <div class="w3-container w3-card w3-white w3-round w3-margin">
        <br>
        <h1>{{posta.user}}</h1><br>
        {{posta.publishing_date}}<br />
        {{posta.title}}<br />
        <p1>{{posta.content}}</p1>

        {%if posta.image %}
        <img src="{{posta.image.url}}" style="width:100%" class="w3-margin-bottom">
        {%endif%}

        <h2>Katılımcılar</h2>
        {%if posta.katilimci %}
        {%for i in katilimcilar%}
        <h1 style="color:forestgreen;">{{i}}</h1>
        {%endfor%}
        {%endif%}<br />
       
    </div>


</body>
</html>

templates/post/form.html
<!DOCTYPE html>
<html>
<title>ActDo</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    html, body, h1, h2, h3, h4, h5 {
        font-family: "Open Sans", sans-serif
    }
    button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }
</style>

<body class="w3-theme-l9">

    <div class="w3-col m7">

        <div class="w3-row-padding">
            <div class="w3-col m12">
                <div class="w3-card w3-round w3-white">
                    <div class="w3-container w3-padding">
                        <form method='POST' enctype="multipart/form-data">
                            {%csrf_token%}
                            {{form.as_p}}
                            
                    </div>

                    <button type="submit" class="btn btn-success">POST</button>
                    </form>
                </div>
            </div>
        </div>


</body>
</html>

templates/post/index.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <div class="row">
        <div class="column" style="background-color:#aaa;">
            <h2>Column 1</h2>
            {%for post in posts%}
            {{post.id}}<br />
            {{post.user}}<br />
            <a href="{{post.get_absolute_url}}">{{post.title}}</a><br />
            {{post.content}}<br />
            {{post.publishing_date}}<br />
            {%if post.image %}
            <img src="{{post.image.url}}" class=" img-responsive"<br />
            {%endif%}
            <a href="http://127.0.0.1:8000/post/create/">
                <button type="button" class="btn btn-default">Katıl</button>
                <button type="button" class="btn btn-default">Detayları ve Katılanlar</button>
                {%endfor%}
        </div>
        <div class="column" style="background-color:#bbb;">
            <h2>Column 2</h2>
            {% for user in users %}
            <h3>{{ user.username }}</h3>
            <button type="button" class="btn btn-default">Arkadası Ekle</button>
            <button type="button" class="btn btn-default">Butun postlar</button>
            {%endfor%}
        </div>
        <div class="column">
            <a href="http://127.0.0.1:8000/post/create/">
                <button type="button" class="btn btn-success">POST OLUŞTUR</button>
        </div>
    </div>
</body>
</html>

templates/post/katilim.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    {%for katil in katilimcilar%}
    {{katil.user}}
    {%endfor%}
</body>
</html>

templates/post/upload.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h3>Show a file-select field which allows only one file to be chosen:</h3>
    <form method="post" enctype="multipart/form-data">
        {{form}}
        Select a file: <input type="file" name="myFile"><br><br>
        <input type="submit">
    </form>

</body>
</html>